services:
  redis-server:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cash-nginx:/data
  node-app:
    build: ./node
    ports:
      - "4000:8000"
  nginx:
    build: ./nginx
    ports:
     - '8050:80'

volumes:
  cash-nginx:


